<!-- Page script level -->
<script type="text/javascript" src="assets/js/banconeg.js"></script>
<script type="text/javascript" src="assets/js/catalogo.js"></script>
<script type="text/javascript" src="assets/js/documenti.js"></script>
<script type="text/javascript" src="assets/js/fatture.js"></script>
<script type="text/javascript" src="assets/js/feedback.js"></script>
<script type="text/javascript" src="assets/js/impostazioni.js"></script>
<script type="text/javascript" src="assets/js/listaordini.js"></script>
<script type="text/javascript" src="assets/js/listaclienti.js"></script>
<script type="text/javascript" src="assets/js/listafornitori.js"></script>
<script type="text/javascript" src="assets/js/nuovordine.js"></script>
<script type="text/javascript" src="assets/js/ordine.js"></script>
<script type="text/javascript" src="assets/js/ordinefornitore.js"></script>
<script type="text/javascript" src="assets/js/pratiche.js"></script>
<script type="text/javascript" src="assets/js/preventivi.js"></script>
<script type="text/javascript" src="assets/js/riparazione.js"></script>
<script type="text/javascript" src="assets/js/scadenze.js"></script>
<script type="text/javascript" src="assets/js/statistiche-ordine.js"></script>
<script type="text/javascript" src="assets/js/ticket.js"></script>
<script type="text/javascript" src="assets/js/usato.js"></script>